version: '3.9'

services:
  backend:
    image: hexagone/reservation_center-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Map container port 8080 to host port 8080
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379" # Map container port 6379 to host port 6379
    volumes:
      - redis_data:/data # Persist Redis data

volumes:
  redis_data: